//! Generate the model × limits matrix for `wiki/limits.md`.
//!
//! Every entry in the bundled registry is printed with its documented
//! context window, output ceiling, per-input limit, embedding dimensions, and
//! character budget — the same figures `GET /v1/models/limits` serves and
//! `GET /v1/models` overlays onto provider listings. Nothing contacts a
//! provider.
//!
//! ```powershell
//! cargo run -p gaise --example limits_matrix > matrix.md
//! ```

use gaise_core::contracts::{GaiseModelLimitsEntry, GaiseOperation};
use gaise_core::registry::{ModelRegistry, limits_matrix};

const PROVIDERS: [(&str, &str); 7] = [
    ("openai", "OpenAI"),
    ("anthropic", "Anthropic"),
    ("gemini", "Google Gemini API"),
    ("vertexai", "Google Vertex AI"),
    ("bedrock", "Amazon Bedrock"),
    ("ollama", "Ollama"),
    ("elevenlabs", "ElevenLabs"),
];

fn tokens(value: Option<u64>) -> String {
    match value {
        Some(v) => format_thousands(v),
        None => "—".into(),
    }
}

fn format_thousands(v: u64) -> String {
    let digits = v.to_string();
    let mut out = String::with_capacity(digits.len() + digits.len() / 3);
    for (i, c) in digits.chars().enumerate() {
        if i > 0 && (digits.len() - i).is_multiple_of(3) {
            out.push(',');
        }
        out.push(c);
    }
    out
}

fn ops(entry: &GaiseModelLimitsEntry) -> String {
    if entry.operations.is_empty() {
        return "—".into();
    }
    entry
        .operations
        .iter()
        .map(|op| match op {
            GaiseOperation::Instruct => "I",
            GaiseOperation::InstructStream => "S",
            GaiseOperation::Embeddings => "E",
            GaiseOperation::Speech => "V",
            GaiseOperation::Live => "L",
        })
        .collect()
}

/// Only the limit-related sentences of an entry's notes, so the table stays
/// readable; the full text is in `models.md`.
fn limit_notes(entry: &GaiseModelLimitsEntry) -> String {
    let Some(notes) = &entry.notes else {
        return String::new();
    };
    let keep: Vec<&str> = notes
        .split_inclusive(". ")
        .map(str::trim)
        .filter(|s| {
            let lower = s.to_ascii_lowercase();
            lower.contains("context")
                || lower.contains("output")
                || lower.contains("character")
                || lower.contains("num_ctx")
        })
        .collect();
    keep.join(" ").replace('|', "\\|")
}

fn main() {
    let registry = ModelRegistry::bundled();
    println!(
        "<!-- Generated by `cargo run -p gaise --example limits_matrix`; registry audited {} -->",
        registry.audited_on
    );
    println!();
    println!(
        "Figures are the vendor-documented limits recorded in [`model-registry.toml`](../gaise-core/model-registry.toml) (`context_window`, `max_output_tokens`, `max_input_characters`, and the embedding profile's `max_input_tokens` / `default_dimensions`). **Ops**: `I` instruct, `S` instruct_stream, `E` embeddings, `V` speech, `L` live. `—` means the vendor publishes no figure; it never means unlimited. Retired entries keep the last documented values."
    );
    println!();
    for (key, title) in PROVIDERS {
        let matrix = limits_matrix(Some(key));
        if matrix.models.is_empty() {
            continue;
        }
        println!("### {title}");
        println!();
        println!(
            "| Model | Status | Ops | Context window | Max output | Max input / text | Dimensions | Chars / request | Notes |"
        );
        println!("|---|---|---|---:|---:|---:|---:|---:|---|");
        for entry in &matrix.models {
            let model = entry
                .id
                .split_once("::")
                .map(|(_, m)| m)
                .unwrap_or(&entry.id);
            let name = if entry.aliases.is_empty() {
                format!("`{model}`")
            } else {
                format!(
                    "`{model}` ({})",
                    entry
                        .aliases
                        .iter()
                        .map(|a| format!("`{a}`"))
                        .collect::<Vec<_>>()
                        .join(", ")
                )
            };
            let status = serde_json::to_value(entry.status)
                .ok()
                .and_then(|v| v.as_str().map(str::to_owned))
                .unwrap_or_default();
            println!(
                "| {name} | {status} | {} | {} | {} | {} | {} | {} | {} |",
                ops(entry),
                tokens(entry.limits.context_window),
                tokens(entry.limits.max_output_tokens),
                tokens(entry.limits.max_input_tokens),
                tokens(entry.limits.embedding_dimensions.map(u64::from)),
                tokens(entry.limits.max_input_characters),
                limit_notes(entry),
            );
        }
        println!();
    }
}
